export const ErrorCode = {
  VALIDATION: 'VALIDATION_ERROR',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  STORAGE_VALIDATION: 'STORAGE_VALIDATION_ERROR',
  STORAGE_UPLOAD: 'STORAGE_UPLOAD_ERROR',
  NETWORK: 'NETWORK_ERROR',
  INTERNAL_SERVER: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];
